### ISSUE TITLE
difference/split system & monitor

### ISSUE THREAD

**Issue by zedd-0** [KrasnovM/Gamma-Manager#5]
hi

your app have config for the "system" (gamma, brightness & contrast)
and for the selected "monitor" (monitor brightness & monitor contrast)

my problem is, i have calibrate my monitors.

if i screw up my "system" setting, i can push the "reset" button.
sadly it resets/change my calibrated monitor.

can you disable reset for 'monitor brightness' and 'monitor contrast',
or split the "system" and "monitor" configuration into two separate reset switches?

thx

**Comment by KrasnovM** [comment]
Hi. I don't know where to fit new button, but i can disable reset for monitor brightness and monitor contrast. Don't know which architecture you need so i compiled all three available
[Release.zip](https://github.com/KrasnovM/Gamma-Manager/files/12172007/Release.zip)

**Comment by zedd-0** [comment]
thanks, this is perfect.


what is [ ] +++ meaning?

it would be nice,
if you could add* 'mouse over' info cards.
which explains the different elements.

(*nice to have, low tier)

**Comment by KrasnovM** [comment]
Nah, i'm too lazy for that. Most of the information explained in readme file in project, other stuff can be found out with a little bit of exploration and parameter tweaking. Good luck!
[ ] +++ unlocks ultra high contrast settings, that's just for memes.

**Comment by zedd-0** [comment]
sorry, but the new version (2023-03-30 - v1.1) do reset monitor brightness & monitor contrast, too.
you forgot to remove this.

**Comment by KrasnovM** [comment]
Well, i use that feature myself so i probably won't remove it. And i don't want to bother with another button. I doubt i will make new versions any time soon so i will just compile code with commented out lines for brightness changes in reset button, like the previous time.
[Gamma Manager 1.1 NoBrReset.zip](https://github.com/KrasnovM/Gamma-Manager/files/12247839/Gamma.Manager.1.1.NoBrReset.zip)
