### ISSUE TITLE
open / close

### ISSUE THREAD

**Issue by BoberxKurwa** [KrasnovM/Gamma-Manager#7]
I start the app and it closes again immediately. Any1 with that issue?

**Comment by KrasnovM** [comment]
Have you tried 32- and 64-bit versions?

**Comment by KrasnovM** [comment]
I remember that I had to allow this app on Microsoft Defender Antivirus. There is the instructions:
https://pureinfotech.com/allow-blocked-file-app-microsoft-defender-antivirus/
One guy in opened issues checked it on VirusTotal and found one false-positive, you can check, if you want:
https://www.virustotal.com/gui/home/upload
For some reason Microsoft Defender finds one issue, different with every release and i couldn't find the solution
