### ISSUE TITLE
Падает при запуске

### ISSUE THREAD

**Issue by Baltazar500** [KrasnovM/Gamma-Manager#8]
Привет.

Хотел поглядеть тулзу, но она у меня даже не стартовала. Падает с вот такой ошибкой.

```

Сигнатура проблемы:
  Имя события проблемы:	CLR20r3
  Сигнатура проблемы 01:	gamma.manager.x64.exe
  Сигнатура проблемы 02:	1.2.0.0
  Сигнатура проблемы 03:	de62ce14
  Сигнатура проблемы 04:	Gamma Manager
  Сигнатура проблемы 05:	1.2.0.0
  Сигнатура проблемы 06:	de62ce14
  Сигнатура проблемы 07:	52
  Сигнатура проблемы 08:	40
  Сигнатура проблемы 09:	System.MissingMethodException
  Версия ОС:	6.1.7601.2.1.0.256.1
  Код языка:	1049
  Дополнительные сведения 1:	50a6
  Дополнительные сведения 2:	50a6feccde870dff76102e8092a0e71d
  Дополнительные сведения 3:	638a
  Дополнительные сведения 4:	638a11e4739dc81c5967ea7e4f2eaddb

```

Валится и x64 и x86 билды.

**Comment by KrasnovM** [comment]
Привет.
Clr20r3 - это проблема с .NET Framework, как показал быстрый гуглёж. У этого приложения версия 4.7.2, насколько я помню. 
На этом форуме очень много обсуждений такой ошибки: http://forum.oszone.net/thread-246138-32.html
Но там такая головная боль с этим дотнетом, что с ума сойти можно.

Я бы сперва попытался обновить .NET Framework без танцев с бубном. Скачать рантайм 4.7.2 или последнюю версию и попробовать запустить.
4.7.2: https://dotnet.microsoft.com/en-us/download/dotnet-framework/net472
4.8.1: https://dotnet.microsoft.com/en-us/download/dotnet-framework/net481
